# Generated by Django 5.0.4 on 2024-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('instituicao', models.CharField(max_length=255)),
            ],
        ),
    ]
